pipeline {
    agent any
    environment {
        RELEASE = "TEST"
    }
    stages {
        stage('Build') {
            environment {
                LOG_LEVEL = "INFO"
            }
            steps {
                if (fileExists('requirements.txt')) {
                        sh """
                        . .env/bin/activate
                        pip install -r requirements.txt
                        """
                }
            }
        }
    }
}
