pipeline {
    agent any
    environment {
        RELEASE = "TEST"
    }
    stages {
        stage('Checkout') {
            steps {
            checkout scm 
            }
        }
         stage('Setup') { 
      steps {
        script {
          sh """
          ../bin/activate
          """
        }
      }
    }
    }
}
