pipeline {
    agent any
    environment {
        RELEASE = "TEST"
    }
    stages {
        stage('Checkout') {
            steps {
            checkout scm 
            }
        }
         stage('Setup') { // Install any dependencies you need to perform testing
      steps {
        script {
          sh """
          pip install -r requirements.txt
          """
        }
      }
    }
    }
}
